name: base_project
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  date_format: ^1.0.8
  intl: ^0.16.1
  shared_preferences: ^0.5.10
  injectable: ^1.0.4
  get_it: ^4.0.4
  auto_route: ^0.5.0
  flutter_hooks: ^0.12.0
  stacked: ^1.7.6
  stacked_hooks: ^0.1.3
  http: ^0.12.2
  rxdart: ^0.24.1
  device_info: ^0.4.2+7
  url_launcher: ^5.5.0
  connectivity: ^0.4.9+2
  flutter_inappwebview: ^4.0.0+4
  image_picker: ^0.6.7+7
  uuid: ^2.2.2
  animations: ^1.1.1

  # FIREBASE
  firebase_messaging: ^7.0.0
  flutter_local_notifications: ^1.4.4+4
  firebase_storage: ^4.0.0
  firebase_auth: ^0.18.0+1
  cloud_firestore: ^0.14.0+2
  firebase_core: ^0.5.0

  # UI
  flutter_svg: ^0.17.4
  shimmer: ^1.1.1
  flutter_html: ^1.0.0
  video_player: ^0.10.12+2
  chewie: ^0.9.10
  youtube_player_flutter: ^7.0.0+7
  carousel_slider: ^2.2.1
  flushbar: ^1.10.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  # run: flutter pub run build_runner build --delete-conflicting-outputs
  build_runner: null
  auto_route_generator: null
  injectable_generator: null

  flutter_launcher_icons: ^0.7.5
  flutter_native_splash: ^0.1.9

# launcher icon generator
# run: flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path_android: "assets/logo/logo_transparent.png"
  image_path_ios: "assets/logo/logo_fill.png"

# splash screen generator
# run: flutter pub pub run flutter_native_splash:create
flutter_native_splash:
  image: assets/logo/logo_transparent.png
  color: "#ffffff"
  fill: false
  android_disable_fullscreen: true

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/logo/
    - assets/videos/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/poppins/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/poppins/Poppins-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/poppins/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/poppins/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/poppins/Poppins-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/poppins/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/poppins/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/poppins/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/poppins/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/poppins/Poppins-BlackItalic.ttf
          weight: 900
          style: italic
